### ISSUE TITLE
Integration Discussion: Steam

### ISSUE THREAD

**Issue by Saturate** [keybase/keybase-issues#1170]
Thread with information and discussion about [Steam](http://store.steampowered.com) integration.
## Proof

Possible: 
- A Group Forum ([Proof Of Concept](http://steamcommunity.com/groups/keybase/discussions/0/619569341121741574/))

Impossible: 
- Profile Resume (Does not support code tag - spaces is lost)
- Profile Info Box (Only some members have these, does not support code tag - spaces is lost)
## Crawler:

_Needs more research. There should an a API for most things._
## TO-DO
- [X] Find places to place proof.
- [ ] Find Crawler API.
- [ ] Finish the TO-DO list.

**Comment by Sarabveer** [comment]
+1

**Comment by fr34kyn01535** [comment]
+1

**Comment by tycho** [comment]
I'd be strongly in favor of this. There's a *ton* of impersonation done on Steam, and it would be nice to have a cryptographically verifiable way to prove someone's identity.

**Comment by malgorithms** [comment]
In an effort to discuss this further, let me write down my understandings. I'm a Steam user but haven't paid a lot of attention to my profile over the years. It seems, correct me if I'm wrong, I have 4 identifiers:

**First, my hidden username**...this is what it says in the top-right corner of Steam, but it's not something other people see about me. (Is that right?)

**Second, my "Profile Name" (`malgorithms`)**, which is what my friends see, but which is not guaranteed to be unique, and it can have spaces. It's basically a name.  Also, I can change it when I want.  For example, here are two people with colliding profile names ("Bob"):

http://steamcommunity.com/id/bob3
http://steamcommunity.com/id/bob

And here's someone with the profile name "Donald Trump":

https://steamcommunity.com/id/donald-trump

**Third, my *custom URL* username**, which also happens to be malgorithms:

http://steamcommunity.com/id/malgorithms

...which I can change whenever I want, I think. For obvious reasons, this one has to be unique.

 **Fourth, finally, a long numerical steamID**, which is probably not that useful for identifying people in a human sense. 


Questions:

1. What do people pass around the most? URL names? Is it safe to say that is what would be proven? That seems to be the only one that makes sense to me.
2. What's wrong with putting a proof directly into the summary screen...anything?  Keep in mind we can encode it without punctuation and do it however want:

![image](https://cloud.githubusercontent.com/assets/614943/18066510/bb6788ac-6e06-11e6-9caa-035c31e7749a.png)


It seems this would be a somewhat simple implementation if proofs were posted in that summary field and people were proving URL id's.

This wouldn't require API access to Steam, since the client can just look directly at that page to verify there's a proof in the summary field:  `https://steamcommunity.com/id/<claimed_username>`

And steamcommunity.com is owned by Valve.

Based on my checks, it updates pretty much instantaneously when I save my profile in the Steam app.

**Comment by juanminm** [comment]
@malgorithms 
> First, my hidden username...this is what it says in the top-right corner of Steam, but it's not something other people see about me. (Is that right?)

Yes, account name is hidden by default. Only you can see it when you log in the web or application

**Comment by tycho** [comment]
Note that since the `/id/<persona>` URLs can be changed by that user at any time and are thus not permanent links to their identity. Malicious users will sometimes create personas that are only off by a single character from a legitimate user as well. The `/profile/<steamID64>` URLs are persistent and stay with the life of the account.

**Comment by zQueal** [comment]
I have to agree with tycho about the steamID. It's more consistent and would only need to be done once per account.

The only actual issue I see is where the proof would be stored. Common sense pretty much demands the summary field would be used to display a proof. However, there's no indication of a text limit. So if there's a limit and a proof is generated that's too long and Steam trims it then the proof would break. In addition to this I did a bit of testing and it seems that if a profile is set to private then the summary field contents is not displayed. This means that Steam profiles need to be set to public, the same as twitter.

I don't see that last part as an issue, I just thought I would point it out.

**Comment by malgorithms** [comment]
keybase itself can always host the proof and hash it down into something small to post on steam. we do this with both twitter and HN. 

url names changing are not a problem, really, except a bit of extra work for the person who changes it.. If someone changes their url name it means they have to redo their proof. the important thing is that a proof claims ownership of a space -- and then the user has to prove they own that space. The big question is *what* is the best space on steam to present on keybase?

I had a bit of a side discussion with @tycho  but on keybase would we rather see

[steam icon] malgorithms      # links to /id/malgorithms
[steam icon ] 7823487234783287  # links to /id/7823487234783287
[steam icon] malgorithms (7823487234783287) # links to /id/malgorithms and breaks if the id changes?

(the third one is awfully long....)

I don't think from a security perspective coming from the keybase side, there's any real advantage to any one of them. They've proven it and keybase is checking the proofs and sending you to whatever they've proven.  There arguably is a UX advantage to the username, if that's what people are going to go type in to search for actual friends on steam...(putting adversaries aside for a second, what's actually *convenient*? ) For example, we link to Twitter names, not twitter id's, even though people can change twitter names, and there are twitter id's? Why, because people don't care what someone's twitter id is. They want to look at the twitter username and see their friend's name.

the human attack we want to be sensitive to is what happens when someone is coming from a proof post on the steam side...if I copy zQueal's Steam profile and make a new one called zQueaI (that's a capital "i" at the end) and I copy the text of zQueal's link - so it links to *his* actual keybase page, someone might start on my fake steam page, click through to keybase, see that they appear to match, and decide that the steam page I started on was legit. 

 Note that this is actually a human attack on the other platforms, too, including twitter. we'll never be able to get around 100% that on some platforms (a) people can make 2 profiles that look indistinguishable, and (b) those platforms aren't verifying the cryptographic claims people are making.

The question is whether including steamID instead really solves this? would the kind of people who manually check that also be the kinds of people that would just click the link back from keybase?

**Comment by tycho** [comment]
Why not this:

[steam icon] malgorithms # links to /profiles/<steamid64>

People should never link to /id/<persona> directly.

**Comment by malgorithms** [comment]
> People should never link to /id/<customurl> directly.

help me understand why not.

I assume in general, it's because they can change.  You like people linking to steamids because the links will survive longer. And because people might change their customURL and not know or control any longer all the places they've linked to it. Someone else could snatch it up later, even. 

(Btw, all these are true for twitter too)

but in the keybase case isn't it different because it breaks the proof? the proof dies as soon as you kill your customURL. 

you asked in our other convo (sorry, trying to get it all converged) a good q:

> Why would you need to review the IDs by hand? 

It most cases you don't.  There are a variety of ways people use keybase<->other service connections.

1. they know someone on a service and search keybase for them by the way they know them
2. they come from somewhere else and land on keybase (from a proof link like a tweet)
3. they know someone on keybase (possibly due to 1 and 2) and discover their other identities...for example, I might look at you and see, "oh wow, you also have website X"
4. they know someone elsewhere and see their profile on keybase coming from someone else they know (common discovery)

in case 2, there are a couple sub-cases:

a. they actually know and trust the person on that other service, in which case they're probably going to trust what they see on keybase, since their friend has chosen to link to this profile. (assuming they think keybase itself isn't targeting an evil answer to them. This isn't in most people's lists of concerns, but in that case they just use the app.)

b. they're looking at a person they don't really know on that other service and see a keybase proof. (or what looks like one - it may be fake).

in case 2b, there's often a basic human review, especially when looking at the keybase website, as opposed to an app.

If I see on JohnDoe on twitter says "Verifying myself, I am foobar1234 on keybase" and you land on foobar1234 and *don't see JohnDoe* you know they're possibly making something up. If you do see JohnDoe then you can assume that Keybase has verified this proof and you can start to learn more about them from all their other proofs.   

This is a basic human check that people make without requiring trusting the crypto. As you and others have pointed out, there may be ways of tricking someone, visually. This will always be possible, whatever we choose, as long as a service lets 2 people make nearly identity looking things. 

The *other* reason you look at them is just to learn about someone. If you and I somehow connect on Keybase and you notice I'm "malgorithms" on steam, then later when you get a request from me, that will push a button in your mind...oh, maybe this is that guy I was talking to before.  This doesn't work if what we present on profiles are things like twitter id's and steam id's.

hhmm..still thinking about all this!

again, thanks for your help.

Aside from this question, if Steam/Valve wants to participate to make rock-solid profile connections, then we can do the best thing of all:

- Steam adds a "keybase proof" field to profiles. just a text box.
- We generate a proof and user posts it
- On Steam, others don't get to see your keybase proof / link unless steam has hit a keybase endpoint that says it's valid.

Then the connection is doubly verified. Someone actually could not lie and claim to be a keybase user they are not.

**Comment by zQueal** [comment]
> I assume in general, it's because they can change.

It's my understanding that the steamID is static and does not change under any circumstances as long as you're dealing with the same user account. I've emailed steam support to confirm this and will update when I hear back.

**Comment by tycho** [comment]
You're correct (source: I work at Valve).

And linking to the /profile/<steamID64> URL will redirect to the current custom URL (if there is one). Not everyone has a custom URL, either. The steamID64 URL will always work.

**Comment by zQueal** [comment]
Quick question for @malgorithms and @tycho (considering he works for valve). Could there be a middle ground between convincing Steam to add a new field specifically for Keybase (which I don't really see why Steam would do this) ~~on the Steam platform where proofs are verified by Steam (and are still public in some way, API maybe?)~~ (not befitting the openness of the Keybase platform?) by logging into that user's account and verifying a Keybase application (oAuth?) which then associates the account with the public proof?

I hate to say it but Steam has nothing to really gain from this (monetarily speaking) so I doubt they'd be interested in putting the dev time in to change their platform in even minor ways to accommodate Keybase. As awesome as it would be.

**Comment by tycho** [comment]
When @malgorithms and I were talking about it, it sounded like the profile "summary" section would do fine.

OAuth would probably be fine as well.

**Comment by malgorithms** [comment]
I'm not following the oauth step. (To clarify, my pie-in-the-sky proposal was a simple system where steam wouldn't let a false claim about a keybase connection appear publicly on a steam profile.)

We haven't done this with anyone, but it would be particularly interesting and protect against the visual impostor step...

As far as I can tell, the only way OAuth would be involved would be if Keybase supported OAuth authentication and Steam made someone go through it before editing some field in their profile. If Valve wouldn't be interested in hitting a simple endpoint to verify something, I doubt they'd be more interested in following a full OAuth process on a 3rd party service, right? 

I was saying:

1. user posts something on steam (probably in a keybase text field)
2. steam lets them save it no matter what, but it only appears public if something like api.keybase.io/checkSteamId?steamid=<x> returns "OK"

I'm not saying we can get valve attention, but it would be very cool, and help greatly in the fight against fake pages on their service. 

it's just wishful thinking, I'm sure... :-)

**Comment by damajor** [comment]
Is there any progress on this topic ? Steam community is pretty large and many users may benefit of using identity proofs.

**Comment by Naville** [comment]
Pop. 
Another solution would be applying a dedicated forum for posting proofs like we did with GitHub. Adding the Keybase app to Steam is a good start as it brings us our own Steam Forum which we can then create dedicated sub-forum for proofs later on. 

``Crawler API`` should have been provided by Steam Web APIs already.

Not sure what are the remaining issues, but if there are no other objections I'd love to help if someone could point me where to start. CC @tycho @malgorithms
